"""auditoria: agrega tokens_exactos y costo_usd_estimado (ADR-0017)

Revision ID: a7f3c9d1e825
Revises: e1b1692f52c7
Create Date: 2026-07-16 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f3c9d1e825'
down_revision: Union[str, Sequence[str], None] = 'e1b1692f52c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditoria_ia', sa.Column('tokens_exactos', sa.Boolean(), nullable=True))
    op.add_column('auditoria_ia', sa.Column('costo_usd_estimado', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auditoria_ia', 'costo_usd_estimado')
    op.drop_column('auditoria_ia', 'tokens_exactos')
    # ### end Alembic commands ###
