"""baseline: esquema inicial (ejecuciones, monitor, usuarios, refresh_tokens, auditoria_ia)

Revision ID: c403b23afae5
Revises: 
Create Date: 2026-07-15 21:57:24.386631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c403b23afae5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_financiero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agente_id', sa.String(length=64), nullable=False),
    sa.Column('indicadores_json', sa.Text(), nullable=True),
    sa.Column('presupuesto_json', sa.Text(), nullable=True),
    sa.Column('flujo_json', sa.Text(), nullable=True),
    sa.Column('uf_valor', sa.Float(), nullable=True),
    sa.Column('dolar_valor', sa.Float(), nullable=True),
    sa.Column('flujo_neto', sa.Float(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analisis_financiero_agente_id'), 'analisis_financiero', ['agente_id'], unique=False)
    op.create_index(op.f('ix_analisis_financiero_ts'), 'analisis_financiero', ['ts'], unique=False)
    op.create_table('auditoria_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('agente_id', sa.String(length=64), nullable=True),
    sa.Column('tipo', sa.String(length=24), nullable=True),
    sa.Column('proveedor', sa.String(length=24), nullable=True),
    sa.Column('modelo', sa.String(length=96), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('herramientas_json', sa.Text(), nullable=True),
    sa.Column('costo_estimado', sa.Integer(), nullable=True),
    sa.Column('veredicto_guardrail', sa.String(length=32), nullable=True),
    sa.Column('duracion_s', sa.Float(), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_ia_agente_id'), 'auditoria_ia', ['agente_id'], unique=False)
    op.create_index(op.f('ix_auditoria_ia_ts'), 'auditoria_ia', ['ts'], unique=False)
    op.create_index(op.f('ix_auditoria_ia_user_id'), 'auditoria_ia', ['user_id'], unique=False)
    op.create_table('ejecuciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agente_id', sa.String(length=64), nullable=False),
    sa.Column('agente_nombre', sa.String(length=128), nullable=True),
    sa.Column('tarea', sa.String(length=256), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=True),
    sa.Column('duracion_s', sa.Float(), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('kpis_json', sa.Text(), nullable=True),
    sa.Column('archivo_id', sa.String(length=32), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecuciones_agente_id'), 'ejecuciones', ['agente_id'], unique=False)
    op.create_index(op.f('ix_ejecuciones_ts'), 'ejecuciones', ['ts'], unique=False)
    op.create_table('gantt_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('agente_id', sa.String(length=64), nullable=True),
    sa.Column('inicio_plan', sa.DateTime(), nullable=False),
    sa.Column('fin_plan', sa.DateTime(), nullable=False),
    sa.Column('duracion_dias', sa.Float(), nullable=False),
    sa.Column('inicio_real', sa.DateTime(), nullable=True),
    sa.Column('fin_real', sa.DateTime(), nullable=True),
    sa.Column('pct_completado', sa.Float(), nullable=True),
    sa.Column('es', sa.DateTime(), nullable=True),
    sa.Column('ef', sa.DateTime(), nullable=True),
    sa.Column('ls', sa.DateTime(), nullable=True),
    sa.Column('lf', sa.DateTime(), nullable=True),
    sa.Column('holgura_dias', sa.Float(), nullable=True),
    sa.Column('en_ruta_critica', sa.Boolean(), nullable=True),
    sa.Column('dependencias_json', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gantt_tasks_agente_id'), 'gantt_tasks', ['agente_id'], unique=False)
    op.create_index(op.f('ix_gantt_tasks_proyecto_id'), 'gantt_tasks', ['proyecto_id'], unique=False)
    op.create_table('guardrail_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agente_id', sa.String(length=64), nullable=False),
    sa.Column('guardrail', sa.String(length=64), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_eventos_agente_id'), 'guardrail_eventos', ['agente_id'], unique=False)
    op.create_index(op.f('ix_guardrail_eventos_guardrail'), 'guardrail_eventos', ['guardrail'], unique=False)
    op.create_index(op.f('ix_guardrail_eventos_ts'), 'guardrail_eventos', ['ts'], unique=False)
    op.create_table('monitor_alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('fuente_nombre', sa.String(length=128), nullable=True),
    sa.Column('titulo', sa.String(length=256), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel', sa.String(length=16), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_alertas_fuente_id'), 'monitor_alertas', ['fuente_id'], unique=False)
    op.create_index(op.f('ix_monitor_alertas_ts'), 'monitor_alertas', ['ts'], unique=False)
    op.create_table('monitor_datos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('fuente_nombre', sa.String(length=128), nullable=True),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('clave', sa.String(length=256), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('valor_numerico', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_datos_categoria'), 'monitor_datos', ['categoria'], unique=False)
    op.create_index(op.f('ix_monitor_datos_clave'), 'monitor_datos', ['clave'], unique=False)
    op.create_index(op.f('ix_monitor_datos_fuente_id'), 'monitor_datos', ['fuente_id'], unique=False)
    op.create_index(op.f('ix_monitor_datos_ts'), 'monitor_datos', ['ts'], unique=False)
    op.create_table('monitor_fuentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=True),
    sa.Column('tipo', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('parametros', sa.Text(), nullable=True),
    sa.Column('intervalo_min', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultima_fetch', sa.DateTime(), nullable=True),
    sa.Column('ts_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('expira', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=True),
    sa.Column('ts_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_username'), 'refresh_tokens', ['username'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.String(length=16), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ts_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_refresh_tokens_username'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('monitor_fuentes')
    op.drop_index(op.f('ix_monitor_datos_ts'), table_name='monitor_datos')
    op.drop_index(op.f('ix_monitor_datos_fuente_id'), table_name='monitor_datos')
    op.drop_index(op.f('ix_monitor_datos_clave'), table_name='monitor_datos')
    op.drop_index(op.f('ix_monitor_datos_categoria'), table_name='monitor_datos')
    op.drop_table('monitor_datos')
    op.drop_index(op.f('ix_monitor_alertas_ts'), table_name='monitor_alertas')
    op.drop_index(op.f('ix_monitor_alertas_fuente_id'), table_name='monitor_alertas')
    op.drop_table('monitor_alertas')
    op.drop_index(op.f('ix_guardrail_eventos_ts'), table_name='guardrail_eventos')
    op.drop_index(op.f('ix_guardrail_eventos_guardrail'), table_name='guardrail_eventos')
    op.drop_index(op.f('ix_guardrail_eventos_agente_id'), table_name='guardrail_eventos')
    op.drop_table('guardrail_eventos')
    op.drop_index(op.f('ix_gantt_tasks_proyecto_id'), table_name='gantt_tasks')
    op.drop_index(op.f('ix_gantt_tasks_agente_id'), table_name='gantt_tasks')
    op.drop_table('gantt_tasks')
    op.drop_index(op.f('ix_ejecuciones_ts'), table_name='ejecuciones')
    op.drop_index(op.f('ix_ejecuciones_agente_id'), table_name='ejecuciones')
    op.drop_table('ejecuciones')
    op.drop_index(op.f('ix_auditoria_ia_user_id'), table_name='auditoria_ia')
    op.drop_index(op.f('ix_auditoria_ia_ts'), table_name='auditoria_ia')
    op.drop_index(op.f('ix_auditoria_ia_agente_id'), table_name='auditoria_ia')
    op.drop_table('auditoria_ia')
    op.drop_index(op.f('ix_analisis_financiero_ts'), table_name='analisis_financiero')
    op.drop_index(op.f('ix_analisis_financiero_agente_id'), table_name='analisis_financiero')
    op.drop_table('analisis_financiero')
    # ### end Alembic commands ###
