"""auditoria: agrega contexto_hats y guardrails_json (ADR-0014)

Revision ID: e1b1692f52c7
Revises: c403b23afae5
Create Date: 2026-07-15 22:30:44.074096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b1692f52c7'
down_revision: Union[str, Sequence[str], None] = 'c403b23afae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditoria_ia', sa.Column('contexto_hats', sa.Text(), nullable=True))
    op.add_column('auditoria_ia', sa.Column('guardrails_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auditoria_ia', 'guardrails_json')
    op.drop_column('auditoria_ia', 'contexto_hats')
    # ### end Alembic commands ###
