"""
core/ports/auth_port.py — Puertos de Autenticación y persistencia de usuarios.

UserRepositoryPort: lo que el servicio de auth necesita de la persistencia
(implementado por core/repositories/user_repository.py con SQLAlchemy).
AuthPort: lo que los adaptadores de entrada (API HTTP, WS, CLI) necesitan
del servicio de auth (implementado por core/services/auth_service.py).
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from core.domain.user import RolType, User


@runtime_checkable
class UserRepositoryPort(Protocol):
    """Persistencia de usuarios. El servicio nunca toca SQL directamente."""

    def contar(self) -> int: ...

    def obtener_por_username(self, username: str, solo_activos: bool = False) -> User | None: ...

    def listar(self) -> list[User]: ...

    def agregar(self, username: str, password_hash: str, rol: str, activo: bool = True) -> User: ...

    def eliminar(self, username: str) -> bool: ...

    def contar_admins_activos(self) -> int: ...

    def actualizar_ultimo_acceso(self, username: str) -> None: ...

    def actualizar_password_hash(self, username: str, password_hash: str) -> bool: ...

    def actualizar_rol(self, username: str, rol: str) -> User: ...

    def actualizar_activo(self, username: str, activo: bool) -> User: ...


@runtime_checkable
class AuthPort(Protocol):
    """Operaciones de autenticación/RBAC expuestas a los adaptadores de entrada."""

    def login(self, username: str, password: str) -> dict | None: ...

    def crear_token(self, username: str, role: str) -> dict: ...

    def verificar_token(self, token: str) -> dict | None: ...

    def tiene_permiso(self, rol_usuario: str, rol_minimo: RolType) -> bool: ...

    def cambiar_password(self, username: str, nueva_password: str) -> bool: ...

    def listar_usuarios(self) -> list[dict]: ...

    def crear_usuario(self, username: str, password_plain: str, rol: RolType = "viewer") -> dict: ...

    def eliminar_usuario(self, username: str, solicitante: str) -> bool: ...

    def cambiar_rol(self, username: str, nuevo_rol: RolType) -> dict: ...

    def activar_desactivar(self, username: str, activo: bool) -> dict: ...
